version: "3"
services:
  task_tracker:
    image: exam_portal
    container_name: exam_portal_backend
    build: .
    env_file:
      - /home/stagging/pdot-env
    ports:
      - 9000:9000
    restart: always
    networks:
      - postgres

networks: 
  postgres: 
    external: true