version: "3"

services:
  task_tracker:
    image: exam_portal
    container_name: exam_portal_backend
    build: .
    ports:
      - 9000:9000
    restart: always
    volumes: 
    - /home/root1/pdot-files/:/app/src/api/uploads/
